Forbid using `float("NaN")`.
wemake-services/wemake-python-styleguide pull request #1654
Opened 2020-10-07 16:54 UTC by lensvol

# I have made things!

## Checklist

- [X] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [X] I have created at least one test case for the changes I have made
- [X] I have updated the documentation for the changes I have made
- [X] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #1383 

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

2020-10-07 17:14 UTC, sobolevn requested changes
Thanks a lot! 👍 

Looks like currently you have covered all `'nan'` args, not just to `float` function.

2020-10-07 17:14 UTC, sobolevn commented on tests/test_visitors/test_ast/test_functions/test_floating_nan.py
> +    'Nan',
What about `NAn` and `nAn`? Just asking.

2020-10-07 17:14 UTC, sobolevn commented on wemake_python_styleguide/violations/best_practices.py
> +        Even if you're 100% sure what you're doing, use math.nan instead.
```
``math.nan``
```

2020-10-07 17:14 UTC, sobolevn commented on tests/test_visitors/test_ast/test_functions/test_floating_nan.py
> +    'a = math.nan',
Let's add `my_function('nan')` case. It should be allowed.

2020-10-07 17:14 UTC, sobolevn commented on wemake_python_styleguide/visitors/ast/functions.py
> +        if node.args[0].s.lower() in frozenset(('nan', b'nan')):
let's move this to a class-level constant!

2020-10-07 21:00 UTC, lensvol commented
There, I fixed it!

2020-10-08 07:40 UTC, orsinium approved these changes
Great work! The tests are fun, I've never seen before more than one `pytest.mark.parametrize` per test function :)

2020-10-08 08:57 UTC, sobolevn requested changes
Thanks! 🚀

2020-10-08 08:57 UTC, sobolevn commented on wemake_python_styleguide/visitors/ast/functions.py
> +        if not isinstance(node.func, ast.Name) or node.func.id != 'float':
We have https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/logic/tree/functions.py#L13 just for this case.

2020-10-08 10:18 UTC, sobolevn approved these changes
Great! 🥇

2020-10-08 10:18 UTC, merged