Fixed #2127 - WPS000 on several code fragments (Fragment 1)
wemake-services/wemake-python-styleguide pull request #2131
Opened 2021-08-07 17:42 UTC by danielboghean

# I have made things!

## Checklist

- [X] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

2021-08-07 17:45 UTC, danielboghean commented
This is my first ever pull request, so please let me know if I'm doing something wrong. I identified the cause of the first fragment of issue #2127 and proposed a solution. 

I tried creating a regression test, but not sure I did it correctly. Any advice or somewhere I can look at documentation would be appreciated!

2021-08-07 18:06 UTC, sobolevn requested changes
You are doing great! Congrats on your first PR 🎉 

Now CI will suggest some small nitpicks to fix before your PR can be merged, please, address the highlighted issues. And I will be happy to merge it!

2021-08-07 18:07 UTC, sobolevn commented
You can also run `flake8 .` locally to find the problems.

2021-08-07 18:49 UTC, danielboghean commented
Thanks @sobolevn! I appreciate it.

I think I fixed all the highlighted issues.

2021-08-07 20:48 UTC, sobolevn approved these changes
Awesome, thank you!

2021-08-07 23:06 UTC, danielboghean commented
Thanks, so much @sobolevn. Is there anything else I need to do on my end for this issue?

2021-08-08 08:41 UTC, sobolevn commented
Yes, there are three failing tests. We need to figure out what to do with them.

2021-08-09 20:15 UTC, danielboghean reviewed
@sobolevn Whenever you have some time, could you take a look at this? I think this is part of why the errors are happening.

2021-08-09 20:31 UTC, sobolevn commented on tests/test_regressions/test_regression2127.py
> +    assert_errors,
Yes, `assert_errors` is defined in `tests/test_visitors.py`: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_visitors/conftest.py#L20 

Move your tests in `tests/test_visitors` subfolder and it should be fine! 👍

2021-08-11 21:58 UTC, danielboghean commented
@sobolevn Sorry to keep bothering you, but I can't seem to figure out what's going wrong with the test. I tried a few different things, but nothing seems to be working. 

It looks like the issue is in the test_no_qa.py file. Any insight on where I should investigate as to why the tests are failing?

2021-08-12 08:30 UTC, sobolevn commented
Hey! There are also style issues:

```
Raw Output:
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
./tests/test_visitors/test_if_else_one_line.py:1:1: I001 isort found an import in the wrong position
./tests/test_visitors/test_if_else_one_line.py:1:81: E501 line too long (81 > 80 characters)
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
=================================

./tests/test_visitors/test_if_else_one_line.py:1:1: F401 'wemake_python_styleguide.violations.refactoring.ImplicitElifViolation' imported but unused
./tests/test_visitors/test_if_else_one_line.py:1:1: I001 isort found an import in the wrong position
./tests/test_visitors/test_if_else_one_line.py:1:81: E501 line too long (81 > 80 characters)
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
./tests/test_visitors/test_if_else_one_line.py:2:1: I005 isort found an unexpected missing import
Process failed with the status code: 1
```

Let's fix them first, so we can actually see failing tests output.

2021-08-12 12:52 UTC, danielboghean commented
Apologies. I fixed the style issues and ran flake8 and mypy locally with no issues, so hopefully that gets all of the style issues.

2021-08-12 13:37 UTC, sobolevn commented
Looks like this error is not triggered: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/fixtures/noqa/noqa.py#L614-L618

2021-08-12 23:20 UTC, danielboghean commented
Thanks for that @sobolevn. That was super helpful in terms of helping me understand what was going on. I think I fixed the issue and passed all tests this time around.

2021-08-21 10:21 UTC, merged

2021-08-21 10:21 UTC, sobolevn commented
@danielboghean thanks again! 👍