Add 'redundant enumerate()' violation.
wemake-services/wemake-python-styleguide pull request #2213
Opened 2021-10-06 16:39 UTC by lensvol

Closes #1825

# I have made things!

## Checklist

- [X] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [X] I have created at least one test case for the changes I have made
- [X] I have updated the documentation for the changes I have made
- [X] I have added my changes to the `CHANGELOG.md`

## Related issues

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

2021-10-06 19:02 UTC, sobolevn requested changes
Thanks a lot!

2021-10-06 19:02 UTC, sobolevn commented on wemake_python_styleguide/violations/best_practices.py
> +    .. versionadded:: 0.18.0
0.16.0

2021-10-06 19:07 UTC, lensvol commented on tests/test_checker/test_noqa.py
> +    'WPS468': 1,
Should I fix that as well?

2021-10-07 16:50 UTC, merged

2021-10-07 16:50 UTC, sobolevn commented
Thanks a lot!