Do not allow super() without parameters in generator expressions #2310
wemake-services/wemake-python-styleguide pull request #2339
Opened 2022-01-27 18:21 UTC by kitsiosvas

# I have made things!

## Checklist

- [ x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

 Closes #2310 

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

2022-01-27 20:21 UTC, sobolevn requested changes
Thanks! 👍

2022-01-27 20:21 UTC, sobolevn commented on wemake_python_styleguide/visitors/ast/classes.py
> +            WrongMethodVisitor(call, text=function_name)
Use `self.add_violation`

2022-01-27 20:21 UTC, sobolevn commented on wemake_python_styleguide/visitors/ast/classes.py
> +        if function_name != 'super':
```suggestion
        if not function_name:
```

2022-02-06 13:10 UTC, kitsiosvas commented
Hello, I was wondering, is there an issue with my contribution on this pull request? I see it being frozen for some days, and I think I can help if there is anything I can do. 
Thank  you

2022-02-06 14:20 UTC, sobolevn commented
@kitsiosvas no worries, you are doing great! I will help you polishing this PR when I will release `0.16.1` (it might take from one to several month). 

You will get full credit for this feature! 🎉 

Thank you for your help!

2023-10-10 18:58 UTC, closed without merging