Fix magic method yields (__next__, __anext__, __aiter__)
wemake-services/wemake-python-styleguide pull request #2400
Opened 2022-04-21 17:51 UTC by Sxderp

# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [x] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues
Closes #2399 

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

2022-04-22 07:35 UTC, sobolevn requested changes
Thanks! 

We totally need:
- A `CHANGELOG` entry for this
- A test case for this, since it is rather complex

2022-04-22 07:35 UTC, sobolevn commented on wemake_python_styleguide/visitors/ast/classes.py
> +                if not (can_async and walk.is_contained(node, (ast.Yield))):
```suggestion
                if not (can_async and walk.is_contained(node, ast.Yield)):
```

2022-04-25 13:49 UTC, Sxderp commented
I'll work on figuring out how to do the tests and hopefully have something by the end of the week.

2022-04-26 16:26 UTC, Sxderp commented
1. I'm not sure how to run the tests.. So letting GitHub do that, hopefully they work.
2. `__aiter__` could have been added to the some of the existing test files, but that's only because those test *happen* to not be async / sync or yield / not yield. I figured it was better to be explicit about these relationships and created new tests for everything.

2022-09-25 10:48 UTC, merged