Add full code to __doc__ and attribute
wemake-services/wemake-python-styleguide pull request #2409
Opened 2022-04-28 15:02 UTC by Bobronium

# I made full violations codes indexable

Finally, people searching for `WPS527 Sovereign Starter Motor` will see that WPS truly means!
<img width="430" alt="image" src="https://user-images.githubusercontent.com/36469655/165780205-28ace86a-c42b-4e4f-9ef4-affcf4e2cdce.png">

## Changes
- Full code is now prepended to `BaseViolation.__doc__`
- Full code is added to `BaseViolation.full_code` class var
- Summary is added to `BaseViolation.summary` class car
- `BaseViolation._full_name` is now a `classmethod`

## How it looks in docs
<img align="right" width="380" alt="image" src="https://user-images.githubusercontent.com/36469655/165781957-f24a6bab-8096-47fe-8a37-2aa413033b1d.png">
<img align="left"width="380" alt="image" src="https://user-images.githubusercontent.com/36469655/165782116-2d78bb81-aed2-488b-bb9d-90181d6e7f33.png">

## Checklist
- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues
Closes #2288
Closes #1145

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

2022-04-29 05:58 UTC, sobolevn requested changes
Thank you, this is amazing!

There are several nitpicks about code style, but other than that - I am happy to merge this! 🎉

2022-04-29 05:58 UTC, sobolevn commented on wemake_python_styleguide/violations/base.py
> +def _prepend_skipping_whitespaces(prefix: str, text: str) -> str:
nit: can you please move this to the very bottom of the file?

2022-04-29 05:58 UTC, sobolevn commented on wemake_python_styleguide/violations/base.py
> +    return f'{leading_whitespaces}{prefix}{lstripped_text}'
```suggestion
    return leading_whitespaces + prefix + lstripped_text
```

2022-04-29 05:58 UTC, sobolevn commented on wemake_python_styleguide/violations/base.py
> +        """
```suggestion
        """Sets additional values for subclasses."""
```

2022-04-29 05:58 UTC, sobolevn commented on wemake_python_styleguide/violations/base.py
> +            cls.__doc__ = _prepend_skipping_whitespaces(f'{cls.full_code} — ', cls.__doc__)
We don't use `f` strings in this codebase 🙂

2022-04-29 05:58 UTC, sobolevn commented on wemake_python_styleguide/violations/base.py
> +        if hasattr(cls, 'code'):
```suggestion
        violation_code = getattr(cls, 'code', None)
        if violation_code is not None:
```

2022-04-29 14:43 UTC, Bobronium commented on wemake_python_styleguide/violations/base.py
> +    def __init_subclass__(cls) -> None:
This causes `WPS338` error. Considering that #2411 is in place, what should be our course of action?

I see the following options:
1. Suppress the error until #2411 gets released
2. Obey current rules of ordering, refactor once #2411 gets released
3. Do nothing, wait until #2411 gets released

2022-04-30 11:33 UTC, Bobronium commented on wemake_python_styleguide/violations/base.py
> +        if violation_code is not None and cls.__doc__:
I'm going to rewrite this to early return now

2022-04-30 16:35 UTC, sobolevn approved these changes

2022-04-30 16:35 UTC, sobolevn commented on wemake_python_styleguide/violations/base.py
> +    def __init_subclass__(cls, **kwargs) -> None:
```suggestion
    # TODO: remove `noqa` after a new release: 
    def __init_subclass__(cls, **kwargs) -> None:  # noqa: WPS338
```

2022-04-30 17:01 UTC, sobolevn commented
Thank you!

2022-04-30 17:01 UTC, merged